'use client';
// import Navbar from '@/components/Navbar';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { NextAuthProvider } from './providers';
import { UserProvider } from '@/components/UserProvider';
import { TopicProvider } from '@/components/TopicContext';
import { useState, createContext, useEffect } from 'react';
import { ThemeProvider } from '@/components/ThemeProvider';
import Menu from '@/components/Menu';

const inter = Inter({ subsets: ['latin'] });
// export const themeColor = createContext({});

// export const metadata: Metadata = {
//   title: 'Plum',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // Create context state
  const [theme, setTheme] = useState('');

  //Get the Color from local storage when the program loads
  useEffect(() => {
    let value = localStorage.getItem('theme');
    if (value !== null) {
      console.log('Retrieved value from local storage:', value);
      setTheme(value);
    } else {
      //if the is no color i local storage set default color
      setTheme('bg-red-plum');
    }
  }, []);

  return (
    <html lang="en" className="bg-zinc-100">
      <body className={inter.className}>
        <TopicProvider>
          <UserProvider>
            <NextAuthProvider>
              <ThemeProvider value={{ theme, setTheme }}>
                {children}
              </ThemeProvider>
            </NextAuthProvider>
          </UserProvider>
        </TopicProvider>
      </body>
    </html>
  );
}
